### ISSUE TITLE
Order of "properties" is lost compared to raml-1-parser

### ISSUE THREAD

**Issue by attah** [raml2html/raml2obj#46]
True, JSON maps are unordered by nature, but order is sometimes significant for documentation to look good. The JSON output from raml-1-parser has the field names in the same order as in the RAML file, but after passing through raml2obj, they are in the regular hash-order. Perhaps properties should not even be a map, but a list, since the order can be important.

I will attempt to look in to this, but some pointers and feedback would be much appreciated.

**Comment by mikedeco** [comment]
Based on the raml using yaml syntax I attempted to put a hyphen in front of the properties. This seemed to maintain the order, but the results from raml2html lost the property names.

Example raml snippet:

```
properties:
  id:
    description: |
      The id.
    type: string
  name:
    description: |
      The name.
    type: string
  description:
    description: |
      The description.
    type: string
  startDate:
    description: |
      The start date.
    type: date-only
```

The above did not guarantee order but would display the names appropriately, something like the following:

**- description:** (string)
  The description.
**- name:** (string)
  The name.
**- id:** (integer)
  The id.
**- startDate:** (date-only)
  The start date.

When adding hyphens to the example snippet:

```
properties:
  - id:
    description: |
      The id.
    type: string
  - name:
    description: |
      The name.
    type: string
  - description:
    description: |
      The description.
    type: string
  - startDate:
    description: |
      The start date.
    type: date-only
```

order was maintained, but the property names lost:

**- :** (integer)
  The id.
**- :** (string)
  The name.
**- :** (string)
  The description.
**- :** (date-only)
  The start date.

I don't know whether the names being lost is a raml2obj or raml2html problem. But it does seem that ordering works it just breaks other things. I would love to look at this myself but my typescript/javascript skills are very lacking.
